services:
  db:
    image: mariadb:10.1.20
    container_name: wordpress_db
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'your_strong_root_password'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'admin'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=wordpress", "--password=admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  wordpress:
    image: wordpress:4.7.1-php5.6-apache
    container_name: wordpress_app
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'admin'
      WORDPRESS_DB_NAME: 'wordpress'
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    depends_on:
      db:
        condition: service_healthy  # To wait for the database to be ready
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
